version: '3.8'
services:
 postgres:
   image: postgres:latest
   container_name: espioescontainer
   environment:
     POSTGRES_DB: CompanhiaDeEspioes
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 1234
   ports:
     - "5431:5432"
   restart: always